#!/bin/bash

# Needs sudo. Try:
# https://js13kgames.com/games/spacebar-clicker/index.html

echo 'Start in 5 seconds...'
ydotoold &> /dev/null &
sleep 5

for _ in $(seq 1 200)
do
    ydotool type ' '
    sleep 0.01
done
