vfs->mkdir("/etw1ld63cgzmq");
vfs->chdir("etw1ld63cgzmq");
vfs->mkdir("/etw1ld63cgzmq/d9afza5vpuemop");
vfs->chdir("d9afza5vpuemop");
{
  int fd = vfs->open("/etw1ld63cgzmq/d9afza5vpuemop/b3.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/etw1ld63cgzmq/d9afza5vpuemop/a-3.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/etw1ld63cgzmq/d9afza5vpuemop/a2.txt", O_CREAT | O_RDWR);
  if (fd > 0) vfs->close(fd);
}
vfs->chdir("..");
vfs->mkdir("/etw1ld63cgzmq/jcf8z7r7pn0r2");
vfs->chdir("jcf8z7r7pn0r2");
{
  int fd = vfs->open("/etw1ld63cgzmq/jcf8z7r7pn0r2/b1.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/etw1ld63cgzmq/jcf8z7r7pn0r2/a3.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/etw1ld63cgzmq/jcf8z7r7pn0r2/a2.txt", O_CREAT | O_RDWR);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/etw1ld63cgzmq/jcf8z7r7pn0r2/a-1.txt", O_CREAT | O_RDWR);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/etw1ld63cgzmq/jcf8z7r7pn0r2/a-3.txt", O_CREAT | O_RDWR);
  if (fd > 0) vfs->close(fd);
}
vfs->chdir("..");
vfs->mkdir("1dgjoc8ebhmhzf");
vfs->chdir("/etw1ld63cgzmq/1dgjoc8ebhmhzf");
{
  int fd = vfs->open("/etw1ld63cgzmq/1dgjoc8ebhmhzf/a3.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/etw1ld63cgzmq/1dgjoc8ebhmhzf/a-3.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/etw1ld63cgzmq/1dgjoc8ebhmhzf/a1.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
vfs->chdir("..");
{
  int fd = vfs->open("/etw1ld63cgzmq/a-1.txt", O_CREAT | O_RDWR);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/etw1ld63cgzmq/a-3.txt", O_CREAT | O_RDWR);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/etw1ld63cgzmq/a1.txt", O_CREAT | O_RDWR);
  if (fd > 0) vfs->close(fd);
}
vfs->chdir("..");
vfs->mkdir("h51ctvjkyfefmod");
vfs->chdir("/h51ctvjkyfefmod");
vfs->mkdir("vc8rip4wswit");
vfs->chdir("/h51ctvjkyfefmod/vc8rip4wswit");
{
  int fd = vfs->open("/h51ctvjkyfefmod/vc8rip4wswit/c-1.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/h51ctvjkyfefmod/vc8rip4wswit/c3.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/h51ctvjkyfefmod/vc8rip4wswit/b3.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/h51ctvjkyfefmod/vc8rip4wswit/c-2.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
vfs->chdir("..");
vfs->mkdir("/h51ctvjkyfefmod/2759ac5ut3d0m");
vfs->chdir("2759ac5ut3d0m");
{
  int fd = vfs->open("/h51ctvjkyfefmod/2759ac5ut3d0m/c-3.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/h51ctvjkyfefmod/2759ac5ut3d0m/a2.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/h51ctvjkyfefmod/2759ac5ut3d0m/b3.txt", O_CREAT | O_RDWR);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/h51ctvjkyfefmod/2759ac5ut3d0m/b-2.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
vfs->chdir("..");
vfs->mkdir("/h51ctvjkyfefmod/mtrlg4zfbr2h");
vfs->chdir("mtrlg4zfbr2h");
{
  int fd = vfs->open("/h51ctvjkyfefmod/mtrlg4zfbr2h/b1.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/h51ctvjkyfefmod/mtrlg4zfbr2h/a-1.txt", O_CREAT | O_RDWR);
  if (fd > 0) vfs->close(fd);
}
vfs->chdir("..");
vfs->mkdir("/h51ctvjkyfefmod/xc531x8lnysaij");
vfs->chdir("xc531x8lnysaij");
{
  int fd = vfs->open("/h51ctvjkyfefmod/xc531x8lnysaij/a1.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/h51ctvjkyfefmod/xc531x8lnysaij/c3.txt", O_CREAT | O_RDWR);
  if (fd > 0) vfs->close(fd);
}
vfs->chdir("..");
vfs->mkdir("/h51ctvjkyfefmod/4pdtl7etzvt0");
vfs->chdir("4pdtl7etzvt0");
{
  int fd = vfs->open("/h51ctvjkyfefmod/4pdtl7etzvt0/a3.txt", O_CREAT | O_RDWR);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/h51ctvjkyfefmod/4pdtl7etzvt0/a-3.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/h51ctvjkyfefmod/4pdtl7etzvt0/c-2.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
vfs->chdir("..");
{
  int fd = vfs->open("/h51ctvjkyfefmod/b1.txt", O_CREAT | O_RDWR);
  if (fd > 0) vfs->close(fd);
}
vfs->chdir("..");
vfs->mkdir("/hsiysh7mcz2xm3");
vfs->chdir("hsiysh7mcz2xm3");
vfs->mkdir("cnjgm3yx8jg5j");
vfs->chdir("/hsiysh7mcz2xm3/cnjgm3yx8jg5j");
{
  int fd = vfs->open("/hsiysh7mcz2xm3/cnjgm3yx8jg5j/b-2.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/hsiysh7mcz2xm3/cnjgm3yx8jg5j/a-3.txt", O_CREAT | O_RDWR);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/hsiysh7mcz2xm3/cnjgm3yx8jg5j/b2.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
vfs->chdir("..");
vfs->mkdir("/hsiysh7mcz2xm3/ef7ceoicta2vkj3");
vfs->chdir("ef7ceoicta2vkj3");
{
  int fd = vfs->open("/hsiysh7mcz2xm3/ef7ceoicta2vkj3/b2.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/hsiysh7mcz2xm3/ef7ceoicta2vkj3/c-1.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/hsiysh7mcz2xm3/ef7ceoicta2vkj3/a-2.txt", O_CREAT | O_RDWR);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/hsiysh7mcz2xm3/ef7ceoicta2vkj3/c3.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
vfs->chdir("..");
vfs->mkdir("dkipsvdc40j5fjw");
vfs->chdir("/hsiysh7mcz2xm3/dkipsvdc40j5fjw");
{
  int fd = vfs->open("/hsiysh7mcz2xm3/dkipsvdc40j5fjw/a-3.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/hsiysh7mcz2xm3/dkipsvdc40j5fjw/c2.txt", O_CREAT | O_RDWR);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/hsiysh7mcz2xm3/dkipsvdc40j5fjw/c-3.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/hsiysh7mcz2xm3/dkipsvdc40j5fjw/b2.txt", O_CREAT | O_RDWR);
  if (fd > 0) vfs->close(fd);
}
vfs->chdir("..");
{
  int fd = vfs->open("/hsiysh7mcz2xm3/b-1.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/hsiysh7mcz2xm3/a-3.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/hsiysh7mcz2xm3/c1.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/hsiysh7mcz2xm3/a3.txt", O_CREAT | O_RDWR);
  if (fd > 0) vfs->close(fd);
}
vfs->chdir("..");
vfs->mkdir("/jw3f4nsa23antht8");
vfs->chdir("jw3f4nsa23antht8");
vfs->mkdir("6706thj11fg0");
vfs->chdir("/jw3f4nsa23antht8/6706thj11fg0");
{
  int fd = vfs->open("/jw3f4nsa23antht8/6706thj11fg0/a-1.txt", O_CREAT | O_RDWR);
  if (fd > 0) vfs->close(fd);
}
vfs->chdir("..");
vfs->mkdir("b5uqfwehwbwwlao");
vfs->chdir("/jw3f4nsa23antht8/b5uqfwehwbwwlao");
{
  int fd = vfs->open("/jw3f4nsa23antht8/b5uqfwehwbwwlao/a2.txt", O_CREAT | O_RDWR);
  if (fd > 0) vfs->close(fd);
}
vfs->chdir("..");
vfs->mkdir("/jw3f4nsa23antht8/asxbojl3h4wq");
vfs->chdir("asxbojl3h4wq");
{
  int fd = vfs->open("/jw3f4nsa23antht8/asxbojl3h4wq/a-3.txt", O_CREAT | O_RDWR);
  if (fd > 0) vfs->close(fd);
}
vfs->chdir("..");
vfs->mkdir("ulfg8tkyjiou6ppl");
vfs->chdir("/jw3f4nsa23antht8/ulfg8tkyjiou6ppl");
{
  int fd = vfs->open("/jw3f4nsa23antht8/ulfg8tkyjiou6ppl/b2.txt", O_CREAT | O_RDWR);
  if (fd > 0) vfs->close(fd);
}
vfs->chdir("..");
vfs->mkdir("/jw3f4nsa23antht8/fp2x7dy0a0u2nx");
vfs->chdir("fp2x7dy0a0u2nx");
{
  int fd = vfs->open("/jw3f4nsa23antht8/fp2x7dy0a0u2nx/c-2.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/jw3f4nsa23antht8/fp2x7dy0a0u2nx/b3.txt", O_CREAT | O_RDWR);
  if (fd > 0) vfs->close(fd);
}
vfs->chdir("..");
{
  int fd = vfs->open("/jw3f4nsa23antht8/a1.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/jw3f4nsa23antht8/b1.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/jw3f4nsa23antht8/a2.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
vfs->chdir("..");
{
  int fd = vfs->open("/b-3.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/b3.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/c-1.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
{
  int fd = vfs->open("/c2.txt", O_CREAT | O_WRONLY);
  if (fd > 0) vfs->close(fd);
}
